services:
  inventory-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: inventory-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SERVER_PORT= 8081
    depends_on:
      - postgres-db
    networks:
      - inventory-service

  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inventory-service

networks:
  inventory-service:
    driver: bridge

volumes:
  pgdata: