name: inventory-service
services:
  inventory-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: inventory-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - inventory-service

  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inventory-service
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  inventory-service:
    driver: bridge

volumes:
  pgdata:
    name: pgdata-inventory