server:
    port: 8082

spring:
    application:
        name: sales-service
  
    flyway:
        enabled: true
        locations: classpath:db/migration

    # Ruta archivo docker-compose dependencia  
    docker:
        compose:
            file: ./sales-service/docker-compose.yaml

    datasource:
        password: postgres
        username: postgres
        url: jdbc:postgresql://localhost:5433/sales_db

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    # Otras config
    config:
        import: classpath:resilience4j.yml

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, circuitbreakers
  endpoint:
    health:
      show-details: always
    info:
      enabled: 'true'

info:
  app:
    name: Store - Sales service
    version: 1.0.0
    description: Microservicio para la gestión de ventas